### ISSUE TITLE
Error: "command not found" on macOS

### ISSUE THREAD

**Issue by mnamutso** [davidhuser/dhis2-pocket-knife#14]
An upgrade to macOS Catalina seems to unrecognize the command.
Strangely `pip show dhis2-pocket-knife` command gives me an existing `dhis2-pocket-knife v0.32.3` however in the location, `/Users/username/Library/Python/2.7/lib/python/site-packages` I notice it is pointing to version 2.7 instead of my previous 3.7 - could this be the problem?

**Comment by davidhuser** [comment]
Hi Martin,

There seem to be PATH issues, I think Apple is also moving to Python 3 by default in some ways.
You can try to

`pip uninstall dhis2-pocket-knife`

then install it with the Python3 version of `pip`:

`pip3 install dhis2-pocket-knife --user` 

And then make sure that the PATH within your `~/.bash_profile` has the right Python version registered as noted here: https://github.com/davidhuser/dhis2-pk/blob/master/docs/installation.md

Let me know how that goes.

**Comment by mnamutso** [comment]
Hi David,

Thanks for the help, it worked perfectly well.

**Comment by davidhuser** [comment]
see also

https://github.com/davidhuser/dhis2-pk/blob/master/docs/installation.md#set-up-your-python-path
