### ISSUE TITLE
dhis2-pk-delete-objects: exit on error

### ISSUE THREAD

**Issue by faebser** [davidhuser/dhis2-pocket-knife#3]
I ran the following command:

``` console
$ dhis2-pk-delete-objects --server=play.dhis2.org/demo --uid_file=UIDS.txt --object_type=dataElements --username=admin --password=district
Deleting FHD3wiSM7Sn
[409] https://play.dhis2.org/demo/api/dataElements/FHD3wiSM7Sn
{"httpStatus":"Conflict","httpStatusCode":409,"status":"ERROR","message":"Could not delete due to association with another object: DataValue"}
```

Maybe you could catch the error and continue with the execution of the remaining items? It is bulk processing, isn't it?

**Comment by davidhuser** [comment]
You're right, currently it exits as soon as an error occurs. Would need to implement this for the others as well and give a feedback what failed.
